apiVersion: "config.istio.io/v1alpha2"
kind: attributemanifest
metadata:
  name: istio-proxy
  namespace: istio-config-default
spec:
   attributes:
      origin.ip:
        valueType: IP_ADDRESS
      origin.uid:
        valueType: STRING
      origin.user:
        valueType: STRING
      request.headers:
        valueType: STRING_MAP
      request.id:
        valueType: STRING
      request.host:
        valueType: STRING
      request.method:
        valueType: STRING
      request.path:
        valueType: STRING
      request.reason:
        valueType: STRING
      request.referer:
        valueType: STRING
      request.scheme:
        valueType: STRING
      request.size:
        valueType: INT64
      request.time:
        valueType: TIMESTAMP
      request.useragent:
        valueType: STRING
      response.code:
        valueType: INT64
      response.duration:
        valueType: DURATION
      response.headers:
        valueType: STRING_MAP
      response.latency:
        valueType: DURATION
      response.size:
        valueType: INT64
      response.time:
        valueType: TIMESTAMP
      source.uid:
        valueType: STRING
      destination.uid:
        valueType: STRING
      # DEPRECATED, to be removed. Use request.useragent instead.
      request.user-agent:
        valueType: STRING
---
apiVersion: "config.istio.io/v1alpha2"
kind: attributemanifest
metadata:
  name: kubernetes
  namespace: istio-config-default
spec:
   attributes:
      source.ip:
        valueType: IP_ADDRESS
      source.labels:
        valueType: STRING_MAP
      source.name:
        valueType: STRING
      source.namespace:
        valueType: STRING
      source.service:
        valueType: STRING
      source.serviceAccount:
        valueType: STRING
      destination.ip:
        valueType: IP_ADDRESS
      destination.labels:
        valueType: STRING_MAP
      destination.name:
        valueType: STRING
      destination.namespace:
        valueType: STRING
      destination.service:
        valueType: STRING
      destination.serviceAccount:
        valueType: STRING

